export enum EventDataSourceValue {
    JWT = "JWT",
    PREHANDLER = "PREHANDLER",
    REQUEST_BODY = "REQUEST_BODY",
    REQUEST_QUERY_PARAMETER = "REQUEST_QUERY_PARAMETER",
    BACKEND = "BACKEND",
    EXPIRED_JWT = "EXPIRED_JWT"
}
