import type { AudienceService } from "./audience/AudienceService";
import type { BigDecimalService } from "./BigDecimalService";
import type { BlockService } from "./BlockService";
import type { CouponService } from "./CouponService";
import type { DateService } from "./DateService";
import type { DoubleService } from "./DoubleService";
import type { EmailVerificationService } from "./EmailVerificationService";
import type { EncoderService } from "./EncoderService";
import type { GlobService } from "./GlobService";
import type { IntegerService } from "./IntegerService";
import type { JsonService } from "./JsonService";
import type { JwtService } from "./JwtService";
import type { Language } from "../Language";
import type { MonthDayService } from "./MonthDayService";
import type { NotificationService } from "./NotificationService";
import type { PersonService } from "./person/PersonService";
import type { PublicClientDomainService } from "./PublicClientDomainService";
import type { RandomService } from "./RandomService";
import type { RewardSupplierService } from "./RewardSupplierService";
import type { ShareService } from "./ShareService";
import type { ShareableService } from "./ShareableService";
import type { StringService } from "./StringService";
import type { UnicodeService } from "./UnicodeService";
import type { UrlService } from "./UrlService";
import type { UserService } from "./UserService";

export interface GlobalServices {
    getAudienceService(): AudienceService;
    getBigDecimalService(): BigDecimalService;
    getBlockService(): BlockService;
    getCouponService(): CouponService;
    getDateService(): DateService;
    getDoubleService(): DoubleService;
    getEmailVerificationService(): EmailVerificationService;
    getEncoderService(): EncoderService;
    getGlobService(): GlobService;
    getIntegerService(): IntegerService;
    getJsonService(): JsonService;
    getJwtService(): JwtService;
    getLanguage(): Language;
    getMonthDayService(): MonthDayService;
    getNotificationService(): NotificationService;
    getPersonService(): PersonService;
    getPublicClientDomainService(): PublicClientDomainService;
    getRandomService(): RandomService;
    getRewardSupplierService(): RewardSupplierService;
    getShareService(): ShareService;
    getShareableService(): ShareableService;
    getStringService(): StringService;
    getUnicodeService(): UnicodeService;
    getUrlService(): UrlService;
    getUserService(): UserService;
}
